### ISSUE TITLE
OnBeforeRendeer hook doesn't work on client side

### ISSUE THREAD

**Issue by blagodus** [brillout/vike-with-pinia#1]
Hi @brillout, great work on the v1 design so far!

I'm trying to move the old Vue + Pinia + VPS project to the V1 design and I found this example repo in the documentation, but I can't set this example to call +onBeforeRender hook on the client side when the `clientRouting` is set to true.
This is the config.h.js I'm using:
```
// https://vike.dev/config
export default {
  // https://vike.dev/clientRouting
  clientRouting: true,
  // https://vike.dev/passToClient
  passToClient: ['initialStoreState', 'pageProps', 'routeParams'],
  meta: {
    onBeforeRender: {
      env: { server: true, client: true }
    }
  }
}
```

Can you please help to resolve this issue?

**Comment by brillout** [comment]
It's quite a common use case, so I'm inclined to think you made a mistake somewhere. Try again and if you still can't make it work then publish a minimal reproduction. (FYI we're working a new config to make that use case a trivial DX.)
